# Generated by Django 3.2.10 on 2022-01-08 03:14

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220108_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=blog.models.name_file),
        ),
    ]
